version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-54-175-117-212.compute-1.amazonaws.com
            database: d9rg12ds9tqq4n
            schema: public
            user: qaimjtetiuexwq
            password: fde839ed8b00fc9ffcd5913d9dd2a94ac85bffea6a20c1e8cb2e732490195a60
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
